### ISSUE TITLE
Suggestion to use TypeScript

### ISSUE THREAD

**Issue by shamoons** [ethereumjs/ethereumjs-client#10]
#### Description
We should consider using TypeScript for this, since it'll make data handling a bit easier to handle

**Comment by holgerd77** [comment]
Hi @shamoons, we had various requests on this on different ``ethereumjs`` libraries (like e.g. https://github.com/ethereumjs/rlp/pull/25). Things are a bit stalled on this front though since noone in the active ``ethereumjs`` team is a TypeScript user and so there is no one who could really maintain this.

If we want to finally have TypeScript support we (someone) have (has) to start in the different underlying ``ethereumjs`` libraries first (``blockchain``, ``block``,...) and probably will also have to commit to support this for some time.

**Comment by LogvinovLeon** [comment]
@holgerd77 I would be happy to start on that and commit some of my time.
I'm on the dev tools team of 0xProject and we have our whole monorepo in TS. I've been using TS for more than a year in production in different environments. I've also just contributed external TS typings to [ethereumjs-tx](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26118) and [ethereumjs-abi](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26117).
Would be happy though to move those typings directly into those projects.

**Comment by stefek99** [comment]
TypeScript is a quantum leap.

In another job took me 2 days to become proficient.

Massive productivity gain onwards.

Full support to this proposal.

Lowest common denominator? HMMM...

**Comment by henriquea** [comment]
I like TS but have mixed feelings about using it in open source projects. It becomes a barrier for a lot of developers keen to contribute. @LogvinovLeon is super talented I'm sure he would do great. Adopting TS would mean to have at least one or two weapons like him fully committed to this project. That's my two cents 😊

**Comment by LogvinovLeon** [comment]
@henriquea It's also hard for new developers to try to guess the types. When working with an untyped code you should be extremely careful and have much more context, because all the errors will reveal themselves only at runtime. I'm not saying TS is free. It adds overhead and complexity. I'm just saying that from all the people I know who've made this choice - I know no one who regrets it. (Disclaimer: I'm obviously biased)

**Comment by EdsonAlcala** [comment]
I have started to code TS recently, I could help and commit some of my time !

**Comment by shumail92** [comment]
Fully support the proposal. Though TS comes with complexity & overhead, I believe that the gains are significant compared to added overhead.

**Comment by holgerd77** [comment]
Just doing some reading on this, started with:

- https://www.typescriptlang.org/docs/handbook/migrating-from-javascript.html
- https://stackify.com/typescript-vs-javascript-migrate/

Sounds doable also for existing projects, I have a strong tendency towards it.

**Comment by holgerd77** [comment]
Just opened a generic issue on our ``organization`` repository: https://github.com/ethereumjs/organization/issues/28

For a broader discussion you can also go there.

**Comment by tomonari-t** [comment]
TS and JS can coexist and dependency libraries(ethereumjs-x) are written by TS.

So I think it's better to move to TS step by step.

**Comment by holgerd77** [comment]
@ryanio will be the man to talk to for this 😄

**Comment by holgerd77** [comment]
Fixed by #144 and following, will close.
