### ISSUE TITLE
Testing Strategy

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-client#21]
#### Description

This library is currently completely untested, there is just a stub test file in the ``tests`` folder allowing for the basic CI setup, which is already running.

While most of the module functionality is tested in the different ``EthereumJS`` repositories like ``ethereumjs-blockchain``, ``ethereumjs-block`` or ``ethereumjs-devp2p``, there have to be integration tests testing the interplay of the different modules in the client context as well as the CL entrypoints of the client.

#### Possible Implementation

Some ideas for tests, partly taken from ``py-EVM``:

- [x] DB and directory initialization tests
- [x] CLI option tests, undefined behaviour
- [x] RPC method tests

#### Reference Implementations / Links

- [py-EVM Trinity tests](https://github.com/ethereum/py-evm/tree/master/tests/trinity)

**Comment by holgerd77** [comment]
Cool! 👍

**Comment by aunyks** [comment]
Is this still an issue or can it be closed?

**Comment by vpulim** [comment]
This can probably be closed since I finished writing all the unit tests that get us to over 90% coverage. I would still like to see some integration tests done to make sure components are working together correctly. I've created a new issue for this: https://github.com/ethereumjs/ethereumjs-client/issues/73 so we can close down this one.
