### ISSUE TITLE
rpc uncaughtException

### ISSUE THREAD

**Issue by unsol** [ethereumjs/ethereumjs-client#91]
I know RPC support is still being worked on, so please feel free to close this issue.

I tried the following methods to run the EthereumJS client:

1. Clone the repo, npm i, npm run build, ./bin/cli.js --rpc
2. Download release v0.0.5, npm i, npm run build, ./bin/cli.js --rpc
3. npm -g install ethereumjs-client, ethereumjs --rpc

Each way results in the following error:

`ERROR [02-20|23:28:43] uncaughtException: Cannot read property 'substr' of null
TypeError: Cannot read property 'substr' of null
    at Array.hex (/home/ubuntu/ethereumjs-client-0.0.5/lib/rpc/validation.js:46:25)
    at Eth.getBlockByNumber (/home/ubuntu/ethereumjs-client-0.0.5/lib/rpc/validation.js:23:41)
    at Method.execute (/home/ubuntu/ethereumjs-client-0.0.5/node_modules/jayson/lib/method.js:123:20)
    at /home/ubuntu/ethereumjs-client-0.0.5/node_modules/jayson/lib/server/index.js:303:12
    at maybeParse (/home/ubuntu/ethereumjs-client-0.0.5/node_modules/jayson/lib/server/index.js:428:5)
    at Server.call (/home/ubuntu/ethereumjs-client-0.0.5/node_modules/jayson/lib/server/index.js:231:3)
    at /home/ubuntu/ethereumjs-client-0.0.5/node_modules/jayson/lib/utils.js:151:14
    at /home/ubuntu/ethereumjs-client-0.0.5/node_modules/lodash/lodash.js:10052:25
    at /home/ubuntu/ethereumjs-client-0.0.5/node_modules/jayson/lib/utils.js:117:7
    at Object.Utils.JSON.parse (/home/ubuntu/ethereumjs-client-0.0.5/node_modules/jayson/lib/utils.js:254:3)`

**Comment by vpulim** [comment]
Thanks @unsol. I’ll take a look

**Comment by unsol** [comment]
Thank you! Keep up the great work! I currently have an EthereumJS Goerli node running. Seems to be ticking along just fine :)

**Comment by vpulim** [comment]
@unsol I'm trying to reproduce the error, but I can only get it to happen if the RPC call is invalid. If I make a valid call (using the example [here](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getblockbynumber)), it seems to work fine. For example, the following works:
```
curl http://localhost:8545 -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x1b4",true],"id":1}' -H "Content-Type: application/json"
```

However, the following invalid call (replacing "0x1b4" with the number 436) does indeed produce the error you saw:
```
curl http://localhost:8545 -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":[436,true],"id":1}' -H "Content-Type: application/json"
```

In any case, I will fix the error so that it doesn't crash the client, but I am curious how you are generating the RPC call that produced the error.

**Comment by unsol** [comment]
Hmm... I was back and forth in to this, so I'm not 100% certain. I think it just happened shortly after starting the EthereumJS client, even without sending a request. Either that, or EthStats connected to it. I'm not quite sure. I can check it out tomorrow for you, if you need more information/logs.

I posted the steps I took to set up EthStats, and EthereumJS, here: https://www.mattbrill.com/2019/02/21/getting-started-with-the-gorli-testnet/

**Comment by vpulim** [comment]
Oops, I accidentally deleted my previous reply. I'm re-pasting here so your reply above makes sense :)

@unsol I'm trying to reproduce the error, but I can only get it to happen if the RPC call is invalid. If I make a valid call (using the example [here](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getblockbynumber)), it seems to work fine. For example, the following works:
```
curl http://localhost:8545 -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x1b4",true],"id":1}' -H "Content-Type: application/json"
```

However, the following invalid call (replacing "0x1b4" with the number 436) does indeed produce the error you saw:
```
curl http://localhost:8545 -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":[436,true],"id":1}' -H "Content-Type: application/json"
```

In any case, I will fix the error so that it doesn't crash the client, but I am curious how you are generating the RPC call that produced the error.

**Comment by vpulim** [comment]
@unsol I'm pretty sure it's EthStats, in which case, it's probably an RPC request format that EthereumJS client should support anyway. Before you do any more detective work let me submit a fix to see if it addresses the problem.

**Comment by vpulim** [comment]
@unsol PR #92 should fix the crash on invalid RPC requests. However, since the EthereumJS client does not yet support all of the RPC methods required by EthStats, it will not work correctly yet.

**Comment by unsol** [comment]
Awesome! Thank you!

Yeah no worries about it not working. It's just a testnet after all :)

Much appreciated!
